[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install && npx prisma generate && npx prisma migrate deploy"

[deploy]
startCommand = "cd backend && node src/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
